### ISSUE TITLE
Rumble 

### ISSUE THREAD

**Issue by raschinger** [eolvera85/PS2toXBOX#1]
Hi, just wondering if the rumble function is functional. Because in my side it's not. But within the library psxnewlib 0.4.0 is rumble available. 

Cheers

**Comment by eolvera85** [comment]
Hi,

At the moment it is not functional, we are in the process of implementation, including the triggers.

I just uploaded a preview version in the rumble_trigger branch, it would help us a lot if you test it and report any problems.

Grettings

**Comment by raschinger** [comment]
Hey, 

many thanks. I've uploaded the programm. Rumble is now possible. But all the other functions aren't possible anymore.  By meaning i cannot use the gamepads buttons and so on.

**Comment by raschinger** [comment]
By meaning e.g test launch doesn't recognize it anymore as an controller. If I flash the old software on it. It working again without rumble.

**Comment by eolvera85** [comment]
I thank you for the tests.

I don't have Arduinos pro micro for testing at the moment. I hope next week I already have some and be able to finish.

Soon we will have the functionality

**Comment by raschinger** [comment]
Sounds great. Where are You from? If you live in europe. I can send you one of my dongles ?

**Comment by eolvera85** [comment]
Sorry for the delay...I'm from Mexico, I appreciate the help, I already have the arduinos, I hope that in some free time, I can perform the tests...

As soon as I have a possible solution, I will update the code

**Comment by raschinger** [comment]
Hi, did you had the chance to look into it ?

**Comment by macamba** [comment]
Hi eolvera85,

I was trying to mount next to bluretro ESP32 as PS2/PSX but XBOX never recognized the connection from my Pro-Micro [[ ](https://es.aliexpress.com/item/1005003622414316.html?aff_fcid=5742e6e77fad4b65ac185c7ec5c33a66-1699193571025-01798-_DljsC2V&tt=CPS_NORMAL&aff_fsk=_DljsC2V&aff_platform=shareComponent-detail&sk=_DljsC2V&aff_trace_key=5742e6e77fad4b65ac185c7ec5c33a66-1699193571025-01798-_DljsC2V&terminal_id=3bf5f74934cf4943a2f345492ef9a09a&afSmartRedirect=y)](url)

My question is if the reference Pro Micro is properly to work or what could be the issu

**Comment by macamba** [comment]
> By meaning e.g test launch doesn't recognize it anymore as an controller. If I flash the old software on it. It working again without rumble.

Hi raschinger, could you pass me the old code? I dont get work current one

Thank you

**Comment by eolvera85** [comment]
> Hi, did you had the chance to look into it ?

I just made a functional commit (Branch rumble_trigger) , I've been testing and everything is functional, triggers and vibration.

**Remember that BlueRetro in PSX/PS2 Mode does not support analog triggers, so you must also modify the BlueRetro project or, if applicable, uncomment and comment on the [lines](https://github.com/eolvera85/PS2toXBOX/blob/rumble_trigger/PS2toXBOX/PS2toXBOX.ino#L75):

```
//gamepad_state.l = psx.buttonPressed(PSB_L2) ? 0xFF : 0x00;
//gamepad_state.r = psx.buttonPressed(PSB_R2) ? 0xFF : 0x00;

gamepad_state.l = psx.getAnalogButton(PSAB_L2);
gamepad_state.r = psx.getAnalogButton(PSAB_R2);
```
also comment this [line](https://github.com/eolvera85/PS2toXBOX/blob/rumble_trigger/PS2toXBOX/PS2toXBOX.ino#L40)

```
        psx.enableAnalogButtons();
```

** BlueRetro by default has vibration disabled, so the function must be enabled.

**Comment by macamba** [comment]
> > Hi, did you had the chance to look into it ?
> 
> I just made a functional commit (Branch rumble_trigger) , I've been testing and everything is functional, triggers and vibration.
> 
> **Remember that BlueRetro in PSX/PS2 Mode does not support analog triggers, so you must also modify the BlueRetro project or, if applicable, uncomment and comment on the [lines](https://github.com/eolvera85/PS2toXBOX/blob/rumble_trigger/PS2toXBOX/PS2toXBOX.ino#L75):
> 
> ```
> //gamepad_state.l = psx.buttonPressed(PSB_L2) ? 0xFF : 0x00;
> //gamepad_state.r = psx.buttonPressed(PSB_R2) ? 0xFF : 0x00;
> 
> gamepad_state.l = psx.getAnalogButton(PSAB_L2);
> gamepad_state.r = psx.getAnalogButton(PSAB_R2);
> ```
> 
> also comment this [line](https://github.com/eolvera85/PS2toXBOX/blob/rumble_trigger/PS2toXBOX/PS2toXBOX.ino#L40)
> 
> ```
>         psx.enableAnalogButtons();
> ```
> 
> ** BlueRetro by default has vibration disabled, so the function must be enabled.

Thanks eolvera85 but I tried to uncomment and comment lines and with rumble and not rumble in bluretro but it was not worked 😓


```
gamepad_state.l = psx.buttonPressed(PSB_L2) ? 0xFF : 0x00;
gamepad_state.r = psx.buttonPressed(PSB_R2) ? 0xFF : 0x00;

 //gamepad_state.l = psx.getAnalogButton(PSAB_L2);
 //gamepad_state.r = psx.getAnalogButton(PSAB_R2);
```


`//psx.enableAnalogButtons();`

**Comment by eolvera85** [comment]
Hello, I have made updates and created a new branch with a new version without the LUFA library, I have not had any problems.

If you are trying to make a combination with BlueRetro, it is beyond my reach.

**Very soon I will launch another project for bluetooh controls for the OGXbox**

**Comment by macamba** [comment]
Hola eolvera,,

He conseguido hacerlo funcionar pero con unos BINs (eep y hex files) de tu codigo viejo, los he conseguido desde un YouTuber "XGAMES VIDEOJUEGOS" q indica como hacer este proyecto funcionar con Bluretro en este video [[ video ](https://youtu.be/1Qo7hu7yt2k?si=RiToiFwhDvLgDrZ9)](url)
Mi principal error era no quitar el diodo, crei q si alimentaba directamente con 3,3v el pro micro funcionaria pero no fue asi

Pero por alguna razon con la actualización de tu codigo q autodetecta si esta en analógico no, no me detecta la pro micro la xbox, también te digo q no he hecho mas pruebas porq es complicado hasta q no suelde el j1 de pro micro, es un engorro estar sujetando los contactos mientras configuro cosas en blueretro, asiq en unos dias en cuanto lo deje todo bien soldado y montado ire haciendo mas pruebas q me interesa que los gatillos sean analogicos

Saludos y gracias por el proyecto
